### ISSUE TITLE
clean up cached smartapi_specs.json

### ISSUE THREAD

**Issue by newgene** [biothings/smartapi-kg.js#36]
The current `smartapi_specs.json` cache file saves the raw output from the SmartAPI API, which contains some dynamic values like:

```
{"took":153,"total":132,"max_score":0.46090317, ...}
```

We should clean them out before saving. Optionally, we can double check if any real content change, otherwise, no need to update the local cache.

**Comment by tokebe** [comment]
It appears the `smartapi_specs.json` in this package is completely static and only serves as a backup in case a `MetaKG` is initialized without the path to the cached version in `bte-trapi`.

See biothings/Biothings_Explorer_TRAPI#250 for a fix addressing this.
